### ISSUE TITLE
Links to submission and distribution api_v1.json files

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-server#1101]
## Your Question

I'm wondering about the api_v1.json links in the https://github.com/corona-warn-app/cwa-server/blob/main/README.md file.

They were recently changed in https://github.com/corona-warn-app/cwa-server/pull/1061 by @hilmarf 

from
https://github.com/corona-warn-app/cwa-server/raw/master/services/submission/api_v1.json and
https://github.com/corona-warn-app/cwa-server/raw/master/services/distribution/api_v1.json

to
https://github.com/corona-warn-app/cwa-server/raw/HEAD/services/submission/api_v1.json
https://github.com/corona-warn-app/cwa-server/raw/HEAD/services/distribution/api_v1.json

where master was replaced by **HEAD**.  I would have expected master to be replaced by main (as the new default branch of the repository). Why wasn't "main" used in the links?

In fact, I'm also wondering why the links aren't using "/blob/main" instead of "/raw/HEAD" such as:

https://github.com/corona-warn-app/cwa-server/blob/main/services/submission/api_v1.json
https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/api_v1.json

**Comment by hilmarf** [comment]
Hi @MikeMcC399,

thanks for your question. The reason I chose `HEAD` instead of `main` is the flexible automated way git keeps updating it to your currently working branch. See https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

This way it's easier to work on multiple different branches in parallel, but always reference within the actual branch from the documentation, instead of 'jumping' to another branch.

I hope that clarifies the idea.

Regards,
Hilmar
