### ISSUE TITLE
Support the TeleTAN and GUID verification server flow

### ISSUE THREAD

**Issue by llewelld** [corona-warn-app/cwa-server#1215]
## Current Implementation

The current implementation provides a "fake" verification server implementation. This supports the `/version/v1/tan/verify'` REST endpoint ("fake" because it accepts only the single TAN of "edc07f08-a1aa-11ea-bb37-0242ac130002").

## Suggested Enhancement

The real verification server also has the following REST endpoints:

1. `/version/v1/registrationToken`
2. `/version/v1/tan`
3. `/version/v1/testresult`

In order to test clients against the test server, it would be useful if the server could also support these endpoints, potentially supporting just a finite set of "fake" inputs, as is already the case for `/version/v1/tan/verify'`.

## Expected Benefits

This would be a useful change for the test server, and for building clients against it.

It would have no effect on the real server implementation.

**Comment by roesslerj** [comment]
Hello llewelld,

thank you very much for your input and sorry you didn't get a response so far. We have been rather busy with implementing stuff, and it's only now we have a little more time on our hands. 

Regarding your PR: We have another setup internally that we use to test the clients against. This is also the reason we didn't need that change. However, since you took the effort in creating this ticket and the PR, we at least didn't want to close it without giving you feedback—for which we didn't find the time.

Now I want to thank you in the name of the team of the CWA for your interest and your effort, even if won't come around to use it. I hope this doesn't discourage you from further participating here or in other open source projects.

Stay healthy!
Jeremias
