### ISSUE TITLE
Wrong EFGS Response Handling

### ISSUE THREAD

**Issue by f11h** [corona-warn-app/cwa-server#1391]
## Describe the bug

The handling of EFGS Multi-Status Response errors is wrong. On Multi-Status response only keys reported with 500 error code are reuploaded. But it is also required to reupload 201 keys.
The 201 Code of Multi-Status-Map means that a key COULD be inserted.

## Expected behaviour

201 Keys are also reuploaded on multi status reponse.

## Possible Fix

https://github.com/corona-warn-app/cwa-server/blob/ffd916d74b499b7fd3e9c7a97b0f9b68204b2f0a/services/upload/src/main/java/app/coronawarn/server/services/federation/upload/runner/Upload.java#L66

Add somethign like the following:

```java
return body.getStatus201()
        .stream()
        .map(Integer::parseInt)
        .map(index -> sortedOriginalList.get(index))
        .collect(Collectors.toList());
```

Thanks to @ubamrein for finding this bug.

**Comment by hilmarf** [comment]
Hi @f11h, thanks for opening this ticket!
Please let us know the actual behavior of the EFGS, when we receive for some keys a 201 and for some a 409, but no 500 at all.

Is the batch processed and all the 201-keys being stored? Yes or No?

Our current solution would first check if there is any 500 error and only if that's the case we'll resend all the 201 + 500 keys. The 409 can be kept out, because they do exist already.

Would that be the correct behavior?

**Comment by f11h** [comment]
Hi @hilmarf ,

in this case the whole transaction will be rollbacked. Because the signature of the batch would not match (because the already existing keys have a different signature)

So the solution would be to take the 500 and 201 keys, put them in a new batch and upload this one.
