### ISSUE TITLE
Consider adding a timestamp to the index files

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#156]
## Current Implementation
Date, hour, country and version index files only contain a JSON array with the respective values.

## Suggested Enhancement
Add a timestamp telling since when the information in the index file is valid.

## Expected Benefits
For example, if there were no submissions in the last hour, the index file would remain unchanged (after #140 and #148 are fixed). This could cause confusion regarding if the day/hour is really just empty or if the distribution run failed. This could also enable the apps to take a simpler caching approach.

## Cross link
#137

**Comment by christian-kirschnick** [comment]
Maybe it would be better to have the distribution service push a "meta" file to the object store instead, which contains this kind of information (e.g. last distribution run). Could be placed directly in the root directory, also as a JSON format for easy consumption.

**Comment by mibrasap** [comment]
Changing the index files will be a breaking change. The mobile app would need to adapt to these changes. A metadata file will not be a breaking change, but bring only a low value-added, since the mobile apps do not evaluate the file yet.
Further investigation regarding this topic can be done after Google/Apple have finished the specification for sharing the diagnosis keys between countries.
