### ISSUE TITLE
CWA Server is responding 502

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-server#1614]
## Describe the bug

https://svc90.main.px.t-online.de is responding 502

## Expected behaviour

The server should not respond 502

**Comment by Ein-Tim** [comment]
Will add more details asap

**Comment by Ein-Tim** [comment]
I can now access https://svc90.main.px.t-online.de/ again, I will leave this issue open for some time, should the issue reappear.

**Comment by mlenkeit** [comment]
@Ein-Tim thanks for reporting the issue! Everything seems to be back to normal now. During the incident, the only functionality in CWA that really was affected was the validation check (aka _Gültigkeit prüfen_ button) in the app, because the business rules could not be retrieved. Any other feature continued to work, because the required resources were either cached by CWA (as expected) or the respective service did not malfunction (such as the service that receives Diagnosis Keys).

**Comment by Ein-Tim** [comment]
@mlenkeit 

Thanks for your answer & a huge thank you to the whole team for fixing this issue very fast! 

I'm now closing this issue as fixed.

**Comment by rugk** [comment]
> respective service did not malfunction (such as the service that receives Diagnosis Keys)

I have heard reports that it actually did malfunction, and people got "Could not check details" instead of any risk assement though, but whatever… it works now again.

**Comment by rugk** [comment]
See also https://github.com/corona-warn-app/cwa-app-android/issues/4442 which further supports this. But as said, let's care about the future…

Is there any post-mortem of the issue or is it just "usual stuff" that Telekom (who hosts the servers AFAIK) does not comment on?
