### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by Gerria321** [corona-warn-app/cwa-server#1991]

**Comment by Gerria321** [comment]
good

**Comment by Ein-Tim** [comment]
Hey there @Gerria321, 

your issue does not hold any details. If you have found a security vulnerable or another security related issue, please follow the instructions provided in the [Security Policy](https://github.com/corona-warn-app/cwa-server/security/policy).

Should you have encountered another, not security related, bug or want to request an enhancement, please provide some details in this thread. Else, I suggest closing this issue.

**Comment by dsarkar** [comment]
Hello @Gerria321, 

We would like to ask you to stop submitting pull requests or opening issues that do not make a meaningful contribution to our project. We are open to receive critique, so, if this is your intention, you are invited to write and express what you wish to say.

Please, as @Ein-Tim already suggested, read our [Code of Conduct] (https://github.com/corona-warn-app/cwa-website/blob/master/CODE_OF_CONDUCT.md) and [Contribution Guidelines] (https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md) and if necessary, also have a look at @MikeMcC399's comment on how to get started using GitHub 
https://github.com/corona-warn-app/cwa-website/pull/3011#issuecomment-1177289094.

We are closing this issue now.

Otherwise, a Merry Christmas to everybody! Best wishes, DS

---
Corona Warning App Open Source Team
