### ISSUE TITLE
 cwa-server englisch 

### ISSUE THREAD

**Issue by Gerria321** [corona-warn-app/cwa-server#1992]

**Comment by Ein-Tim** [comment]
I suspect this issue to be spam. The user @Gerria321 has opened two spam PRs in the https://github.com/corona-warn-app/cwa-website repository (https://github.com/corona-warn-app/cwa-website/pull/3011 & https://github.com/corona-warn-app/cwa-website/pull/3012 before.

I suggest giving @Gerria321 the chance to explain themselves and make clear for which reason they are opening empty issues / providing PRs without sensible content. If there is no explanation or excuse, I recommend to officially warn the user, as their behavior may be interpreted as a violation of the [Code of Conduct](https://github.com/corona-warn-app/cwa-server/blob/main/CODE_OF_CONDUCT.md) (trolling).

cc @SebastianWolf-SAP

**Comment by dsarkar** [comment]
Hello @Gerria321, 

We would like to ask you to stop submitting pull requests or opening issues that do not make a meaningful contribution to our project. We are open to receive critique, so, if this is your intention, you are invited to write and express what you wish to say.

Please, as @Ein-Tim already suggested, read our [Code of Conduct] (https://github.com/corona-warn-app/cwa-website/blob/master/CODE_OF_CONDUCT.md) and [Contribution Guidelines] (https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md) and if necessary, also have a look at @MikeMcC399's comment on how to get started using GitHub 
https://github.com/corona-warn-app/cwa-website/pull/3011#issuecomment-1177289094.

We are closing this issue now.

Otherwise, a Merry Christmas to everybody! Best wishes, DS

---
Corona Warning App Open Source Team
