### ISSUE TITLE
Re-introduce batching for diagnosis key packages

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#204]
## Feature description
The current CWA server implementation assumes that single packages will never go over 16MB (as per [Google/Apple spec](https://developer.apple.com/documentation/exposurenotification/setting_up_an_exposure_notification_server)), therefore batching code has been removed.
- [ ] Assess under which circumstances packages could go above 16MB
- [ ] Re-introduce batching if necessary

**Comment by pithumke** [comment]
[app.coronawarn.server.services.distribution.assembly.diagnosiskeys.util.Batch](https://github.com/corona-warn-app/cwa-server/blob/3b3fc57e8ea6c700c44a4a4f87aed6fc595a39b1/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/util/Batch.java) (from an older code state) could potentially be reused for this.

**Comment by ebratter** [comment]
Per recent discussions with @christian-kirschnick it was agreed to keep this issue open in order to enable the following:

- Follow-up based on federation gateway integration based on what we see for the magnitude of keys
- What might change once we receive the new EN specification from Apple/Google
- To ensure whatever approach was considered in the past could be documented.

**Comment by mibrasap** [comment]
In future releases, the mobile apps will consume hourly-based key packages and hence the data volume will be decreased. Therefore, we will not investigate further on this.
