### ISSUE TITLE
DiagnosisKeyService Paging 

### ISSUE THREAD

**Issue by kevin0x90** [corona-warn-app/cwa-server#213]
## Current Implementation
```java
public List<DiagnosisKey> getDiagnosisKeys() {
  return keyRepository.findAll(Sort.by(Direction.ASC, "submissionTimestamp")).stream()
      .filter(DiagnosisKey::isValid).collect(Collectors.toList());
}
```
## Suggested 
Consider paging (depending on the amount of data that might be possible)

## Expected Benefits
Less memory consumption for huge datasets

**Comment by odrotbohm** [comment]
While I generally agree, it looks like the client code ends up using the result list entirely in `DiagnosisKeysDirectoryImpl`. Thus, switching to paginated access would only increase the number of database roundtrips and unnecessary metadata accumulated (the additional count query needed in particular).

So unless the chunk based lookup can actually be translated into e.g. improved client communication, I'd recommend to refrain from applying the suggestion.

**Comment by ebratter** [comment]
Per recent discussions with @christian-kirschnick we agreed that this doesn't make a ton of sense at the moment to proceed with due to the additional round trips to the DB. Also based on the existing load test scenarios we think the load is manageable based on the memory allocation to the services. Based on the approach considered for the federation topics this should also not have a large impact as the countries would be spread over several jobs. Therefore, we agreed to close this for the time being.
