### ISSUE TITLE
CodeStyle / Formatting.

### ISSUE THREAD

**Issue by indyaah** [corona-warn-app/cwa-server#241]
* Source File: N/A
* Line(s): N/A
* Question:  Is there a shared code style adopted for the project? 

If not, I'd propose that https://github.com/google/google-java-format be adopted.

Pros: 
- Wider adoption
- [Solid tooling integration](https://github.com/google/google-java-format#third-party-integrations) (IntelliJ Plugin, Maven Plugin, Pre-commit hook support)
- Peace of mind while filing / reviewing PRs

Cons: 
- Possibly intrusive to people's personal setup.

Happy to take on and get maven plugin integrated if this sounds it would provide some value.

**Comment by jonaskoepper** [comment]
To my understanding, this is already the case - Google Java Code Style was chosen.

- See https://github.com/corona-warn-app/cwa-server/tree/master/codestyle

- The according Checkstyle Maven plugin is also present: https://github.com/corona-warn-app/cwa-server/blob/master/pom.xml#L32

**Comment by stevesap** [comment]
@michael-burwig can you confirm this is already the case?

**Comment by CCFenner** [comment]
For simple formatting I can recommend [`.editorconfig`](https://editorconfig.org) which helps to take care about *dangling spaces*, *line breaks*, *indentation* and *indent type (space/tab)*.

IDE's like VSCode can then automatically stick to the defined rules with an additional plugin.

**Comment by indyaah** [comment]
@stevesap : Yes, preferably automating code formatting before committing.  

Other option is to share IDE specific style configs and updating CONTRIBUTING.md to mention that your IDE needs to be setup to use them.

The issue with checkstyle is for some reason it's not really enforcing Google Java Style and it is reactive in nature. 

I have habit of autoformatting files after I have made changes to (IntelliJ with Google Code Style) and every single file I touch ends up having formatting changes that are 8-10x my actual change.

**Comment by stevesap** [comment]
Hi @indyaah, we discussed and it sounds like it could be a nice addition to have an auto formatter integration to encourage wider adoption so feel free to proceed. 

Please keep in mind that as mentioned in the [CONTRIBUTING.md](https://github.com/corona-warn-app/cwa-server/blob/master/CONTRIBUTING.md#engaging-in-our-project), we are adhering to the Google Java Style, with the one exception of a max line width of 120 characters.

Just a head up that we will evaluate the solution first to make sure it works smoothly as we would expect or otherwise we may have to hold off on it since we are approaching a critical deadline and need to keep potential slowdowns to a minimum. Thanks!

**Comment by indyaah** [comment]
@stevesap : Thanks, I think I will hold off in that case, IMO this is low prio and specially if there is a deadline approaching I would not add something that forces each developer to break their normal working flow with repo.

**Comment by arteam** [comment]
Just wanted to mention that despite [google-java-format](https://github.com/google/google-java-format) supports formatting code automatically via [https://github.com/coveooss/fmt-maven-plugin](fmt-maven-plugin) or and the IntelliJ plugin, it hardcodes the 100-character limit and doesn't have an option to change that. So that would be a blocker if team wants to maintain the 120-character line limit.

**Comment by nils4cosee** [comment]
This is is a Intellij-style-file that can be imported.

[GoogleStyle-width120.zip](https://github.com/corona-warn-app/cwa-server/files/4778750/GoogleStyle-width120.zip)

**Comment by indyaah** [comment]
Marking as closed given there is high probability of failure and a known work around, thanks @arteam / @nils4cosee
