### ISSUE TITLE
Add correct Verification Key ID and Version

### ISSUE THREAD

**Issue by pithumke** [corona-warn-app/cwa-server#266]
## Current Implementation
The Verification Key ID and Verification Key Version inside the "Signature Info" are blank. See [here](https://github.com/corona-warn-app/cwa-server/pull/240/files#diff-a5805e5e55bd745458a2dfac8cf91938R88).

## Suggested Enhancement
Add the correct Verification Key ID and Verification Key Version.

## Details
These values will eventually be provided by Google/Apple, when we send them our prod certificate. This issue is blocked until that happens.

**Comment by christian-kirschnick** [comment]
The final values

```
signature_infos {
  app_bundle_id: " de.rki.coronawarnapp"
  verification_key_version: "v1"
  verification_key_id: "262"
  signature_algorithm: "1.2.840.10045.4.3.2"
}
```

**Comment by ChristopherSchmitz** [comment]
I would like to share more context information.
**1) Parameter configuration per landscape:**
Since we use different key-pairs in production and non-production landscapes we will use on the mobile vendors side different bundle id's (they only support one key pair per bundle id)

This leads to the requirement: Configure the parameters per landscape.

**2) For development we plan the following configuration:**
(it is currently in configuration and will be confirmed hopefully soon)

signature_infos {
  app_bundle_id: " de.rki.coronawarnapp-dev"
  verification_key_version: "v1"
  verification_key_id: "262"
  signature_algorithm: "1.2.840.10045.4.3.2"
}
