### ISSUE TITLE
Usage of MD5  

### ISSUE THREAD

**Issue by phros** [corona-warn-app/cwa-server#344]
In `app.coronawarn.server.services.distribution.objectstore.publish.LocalFile#computeS3ETag` [(link to source)](https://github.com/corona-warn-app/cwa-server/blob/63dda0c2a5e1ff09fe998dd05637d76dea2e3833/services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/publish/LocalFile.java#L76), a tag for a file is calculated by using MD5. As far as I know, this tag is used for detecting whether a file has been changed. Today, MD5 should not be used as hash function as an attacker can craft files with modified content but same MD5-sum.

In case it is possible for you to change the used hash function, you should use SHA-256, SHA-384 or SHA-512.

**Comment by oiime** [comment]
@phros I think MD5 for ETag is a sad S3 legacy, They are using some none-AWS implementation of it so I'm not sure if it is feasible in this case to use an alternative digest (due to protocol restrictions). 

That being said, I dont think the file digest in this implementation is actually used for any security purposes anyway, they're just using it to check the file's state

**Comment by stevesap** [comment]
We use the ETags for caching purposes only and do no integrity checks based on this header. We follow common standards (e.g. S3 ) by using MD5. However, we see a theoretical risk wrt. denial of service, but agreed to accept this risk as it would require sophisticated prerequisites. The integrity of files is ensured by explicit signatures and not depending on the ETag.
