### ISSUE TITLE
diagnosis_key table structure

### ISSUE THREAD

**Issue by oiime** [corona-warn-app/cwa-server#345]
## Your Question

* Source File: /common/persistence/src/main/resources/db/migration/postgres/V1__createTables.sql
* Line(s): -
* Question: I'm trying to figure out the rationale for the structure here:

1. why do you need an autoincrement ID here?  why not use the key as the primary, assuming you're using UUIDv4 it's very unlikely to have a collision and even if you do you definitely do not want a duplication, you don't seem to make use of its sequential nature anyway

2. why is key_data a bytea? it surely isn't of a varying size, wouldn't it make sense to just use the built in UUID type in postgres which also has the added benefit of fast comparison?

3. why use bigint for submission_timestamp when there are built in timestamp data types that can provide faster lookup?

**Comment by stevesap** [comment]
Related: #289

**Comment by stevesap** [comment]
1. `id` column will be removed (as indicated in #289)
2. In review
3. Because the submission timestamp is not counted in unix seconds since epoch (like regular timestamps), but it 1-hour intervals since epoch (to reduce accuracy). We need to convert stuff anyways, might as well use an int. Also, the type was changed from bigint to integer in this PR:
https://github.com/corona-warn-app/cwa-server/pull/256

**Comment by stevesap** [comment]
closing as only outstanding issue is addressed in #289

**Comment by alvar-freude** [comment]
As mentioned in https://github.com/corona-warn-app/cwa-server/issues/451#issuecomment-640202682, I suggest to use a check constraint to limit the accuracy of the timestamp. This allows all calculations to be performed with time functions and does not require any possibly error-prone conversion.
