### ISSUE TITLE
docker-compose setup for running cwa-server in the IDE?

### ISSUE THREAD

**Issue by nils4cosee** [corona-warn-app/cwa-server#476]
## Your Question

I would like to run the `cwa-server` in the IDE, but without having to install PostgreSQL and Zenko-Cloudserver myself. It would be cool if the environment started with `docker-compose up` would use the same ports that the dev-profile uses to access the components. 

Is there something that I have missed? Otherwise I would try to either create another docker-compose file or modify the existing one.

**Comment by josuablejeru** [comment]
Hallo @nils4cosee as I can see right now you should be able to work on the application with this Docker Compose File.

Let me know if you need any assistance 😄

**Comment by pithumke** [comment]
Hello @nils4cosee,
we decided to go for non-default ports for e.g. Postgres and Zenko to not interfere with already existing installations of these components on developer's machines. In order to make your local IDE work with the components deployed through `docker-compose`, you can edit your IDE's run configurations, namely:

For the distribution module:
```
POSTGRESQL_SERVICE_PORT=8001
VAULT_FILESIGNING_SECRET=</path/to/your/private_key>
```

For the submission module:
```
POSTGRESQL_SERVICE_PORT=8001
```

Please let us know if this answers your question.

**Comment by nils4cosee** [comment]
Yes, that seems to work, for the submission module at least. I haven't tried the other one yet. Thanks,
