### ISSUE TITLE
allocating full byte array of File/Archive abstraction may lead to OutOfMemoryError?

### ISSUE THREAD

**Issue by jsievers** [corona-warn-app/cwa-server#517]
## Your Question

* Source File: https://github.com/corona-warn-app/cwa-server/blob/ffde29b4610c22a2731237566e00fff9c3c8cc51/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/structure/file/File.java#L35
* Question: I noticed that the File/Archive abstraction does not stream file contents to disk but rather allocates one byte[] array with the full content of the file in-memory.

I can see that file sizes are limited to ~16 MB https://github.com/corona-warn-app/cwa-server/blob/ffde29b4610c22a2731237566e00fff9c3c8cc51/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/io/IO.java#L36

(see related issue https://github.com/corona-warn-app/cwa-server/issues/204 )

but I wonder how many of those File/Archive objects are held in memory simultaneously and whether this could lead to OutOfMemoryError given enough files/large enough files. (e.g. 100 files of 16 MB each would allocate 1,6 GB in memory)

From https://github.com/corona-warn-app/cwa-server/blob/ffde29b4610c22a2731237566e00fff9c3c8cc51/services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/Assembly.java#L73 it looks to me as if all files of the directory tree are held in memory simultaneously but I may be wrong.

**Comment by stevesap** [comment]
Hi @jsievers, thank you for raising this concern. Your assessment is correct, all those files are held in memory simultaneously and, moreover, could (theoretically) also go above 16MB, as the files that go above that limit are only filtered out during the "write" step (when they are written to disk), but not during the "prepare" step (where their content is being assembled).

While it is true, that this could theoretically lead to OutOfMemoryExceptions, we currently don't see a scenario in "normal operations" where this could actually occur. In order for a day-aggregate file to go above 16MB, it would need to contain around a million Temporary Exposure Keys (submitted during a single day). The same applies to the hour files, for which this scenario is even less likely to happen.

However, we of course encourage this "memory hungriness" to be improved (e.g. by merging the "prepare" and "write" steps into a single step, by paginating diagnosis key queries from the DB and querying them on-demand, or by using streams instead of allocations). We have opened up a respective "enhancement ticket" #538.

Again, thanks for helping us improve CWA!
