### ISSUE TITLE
Failing requests in down-scaling scenario

### ISSUE THREAD

**Issue by michael-burwig** [corona-warn-app/cwa-server#547]
## Describe the bug

Reducing the number of submission service service pods leads to immediate termination of request processing on the service instance that is shutting down while. This results in clients observing a failing requests.
In the worst case scenario, submission processing is interrupted after a TAN was verified successfully but the corresponding diagnosis keys have not been persisted yet.

## Expected behaviour

On a service instance that is shutting down, no new requests shall be accepted. Requests that are already being processed at the time shall be given a grace period in which they are allowed to finish processing.

## Possible Fix

- ``ThreadPoolExecutor.awaitTermination`` and similar concepts

## Additional context
From a previous performance testing run:

![image](https://user-images.githubusercontent.com/64439292/84418312-4c25ea80-ac17-11ea-9b2e-ca398f877508.png)

**Comment by RomanNess** [comment]
On the Kubernetes/Openshift side the `terminationGracePeriodSeconds` parameter on the Pod spec should default to 30s between the `SIGTERM` and `SIGKILL` commands in order to perform a graceful pod shutdown.

The used `SIGTERM` command can be configured via `lifecycle.preStop` parameter on the pod spec.

See pod termination lifecycle: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods


Judging by the described behavior, we know that no graceful shutdown is performed inside the service when it should receive a `SIGTERM`. However, we don't know how it is configured on Kubernetes side and whether there is a graceful shutdown at all. Related to issue [cwa-documentation/issues/222](https://github.com/corona-warn-app/cwa-documentation/issues/222), it would be helpful to see the Helm chart, K8s yaml, etc that is used to deploy the service to Kubernetes in order to appropriately resolve this bug.
