### ISSUE TITLE
Performance Improvement: Disable spring.jpa.open-in-view in submission service

### ISSUE THREAD

**Issue by shyamz-22** [corona-warn-app/cwa-server#556]
## Current Implementation
In the current implementation In-view interceptor has no explicit configuration in the [application.yml](https://github.com/corona-warn-app/cwa-server/blob/master/services/submission/src/main/resources/application.yaml). The default setting is `true`

## Suggested Enhancement

```yml
spring.jpa.open-in-view: false
```

## Expected Benefits
How disabling this property may increase performance is explained in detail here: https://www.baeldung.com/spring-open-session-in-view

The most important benefit is to control the problems that can arise due to connection pool exhaustion

As explained in [section 4.2](https://www.baeldung.com/spring-open-session-in-view#2-exhausting-the-connection-pool)

> When OSIV is active, there is always a Session in the current request scope, even if we remove @Transactional. Although this Session is not connected initially, after our first database IO, it gets connected and remains so until the end of the request.

> Here's what happens while the OSIV is enabled:

> - At the beginning of the request, the corresponding filter creates a new Session.
> - When we call the findByUsername method, that Session borrows a Connection from the pool.
>  - The Session remains connected until the end of the request.

> Even though we're expecting that our service code won't exhaust the connection pool, the mere presence of OSIV can potentially make the whole application unresponsive.

> To make matters even worse, the root cause of the problem (slow remote service) and the symptom (database connection pool) are unrelated. Because of this little correlation, such performance issues are difficult to diagnose in production environments.

### Spring also prints out the warning when the server starts

``` bash
submission_1         | 2020-06-12T07:13:46Z WARN  main o.s.b.a.o.j.JpaBaseConfiguration$JpaWebConfiguration[1]: spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
```

**Comment by hilmarf** [comment]
Thanks for the enhancement @shyamz-22 

we did some load tests and evaluated the different setting effects.

![total_requests_per_second_false](https://user-images.githubusercontent.com/5467580/86006079-c1fec400-ba15-11ea-88c1-7ba3bb7717ba.png)
![total_requests_per_second_true](https://user-images.githubusercontent.com/5467580/86006081-c2975a80-ba15-11ea-930b-98a4b18f74bb.png)
![response_times_false](https://user-images.githubusercontent.com/5467580/86006083-c32ff100-ba15-11ea-9717-5bbcbcf4399f.png)
![response_times_true](https://user-images.githubusercontent.com/5467580/86006085-c32ff100-ba15-11ea-9fce-3775d3376422.png)

And because we have only one single entity in our [domain](https://github.com/corona-warn-app/cwa-server/tree/master/common/persistence/src/main/java/app/coronawarn/server/common/persistence/domain) it doesn't make sense to have this `open-in-view=true`.

**Comment by jsand66** [comment]
Hi, Can anyone tell me how to disable it through programmatically. I am loading jpa properties using bean configuration

**Comment by AleixMT** [comment]
> Hi, Can anyone tell me how to disable it through programmatically. I am loading jpa properties using bean configuration

I would like to know how to do so too!
