### ISSUE TITLE
dummy diagnosis keys are sometimes too easy to spot because of wrong matching of risk value and date

### ISSUE THREAD

**Issue by hagct** [corona-warn-app/cwa-server#622]
## Current Implementation

Today the first batch of 341 Diagnosis Keys was relased. Each key has a corresponding risk value and a date. The risk values are numbers from 1 to 8, but are dependend on the date. A low risk value of "1" must at least be seven days old. But in the list of Diagnosis Keys there are several entries, where a risk value of 1 is combined with a date just two days ago. These must be dummy keys and are easy to spot. 

## Suggested Enhancement

When generating dummy keys, dont add risk values and dates at random, but combine them. Use the same criteria as in the real risk calculation.

## Expected Benefits

this would improve data security and would it make harder to seperate the real keys from the dummies.

**Comment by christian-kirschnick** [comment]
Those keys are actually real keys. Reason why they stand out is that there was a bug on the mobile app, which resulted in using wrong values for the transmission risk level. This was fixed with https://github.com/corona-warn-app/cwa-app-android/pull/679.

The system currently does not make up fake keys on its own, but rather uses duplication to create noise.
