### ISSUE TITLE
Wrong hash value for 2020-06-23 and 2020-06-24

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#650]
## Current Implementation

Old keys are deleted and the remaining keys are repacked by day or by hour.
60 keys moved from 24.06.2020 to 23.06.2020.
44 keys are deleted from 23.06.2020
The hour files 2020-06-23-hour-08.zip, 2020-06-23-hour-13.zip, 2020-06-23-hour-17.zip are repacked to
2020-06-23-hour-10.zip, 2020-06-23-hour-15.zip, 2020-06-23-hour-18.zip
(Even the old hour files are superseded they are still on the server.)
## Suggested Enhancement

Leave the files as they are, do not remove old keys. 
## Expected Benefits

The files downloaded by the app have the same hash value as the file on the server.

**Comment by christian-kirschnick** [comment]
Initial suspicion: Retention Policy kicked in and deleted older keys, which were not immediately distributed due to shifting policy. This in turn did lead to even less keys for the first days of CWA so the other packages were now also shifted.

I believe this only affects hourly packages as retention enforcement & daily package creation are part of the same job. 

There are some options on how this can be fixed:
1. (Temporary) Disable hourly files. As they are currently not being used by the mobile app, there would be no impact.
2. Run retention only once per day and not on every job. Can be problematic in case this one job did not trigger or failed, so the next retention run would only occur after 24 hours. Not a big issue though.
3. Store some pointer/information on the database which indicates which keys were already distributed. There are some edge cases which make this approach more complicated though (e.g. shifting keys due to 2 hours key validity expiration).

**Comment by Tho-Mat** [comment]
Today 2020-06-24.zip on the server has the same values and hash as it was first publish (so the 60 moved keys moved back).

2020-06-23.zip does not contain 173 keys of the original file. But this time, on IOS, the file has been downloaded again, why??
The hash and the # of keys are the same in IOS and on the server (330 keys now). 

All keys publish in 2020-06-23-hour-08.zip are missing in the daily file 2020-06-23.zip, now. 
Is this expected?

**Comment by pithumke** [comment]
Hello @Tho-Mat,

thank you very much for raising this issue! You are right, the behavior that you observed is not intended. We investigated the issue and, as @christian-kirschnick rightly popinted out, this behavior is an unintended side-effect of two DPP policies that (each one separately) are behaving as expected: The retention policy and the shifting policy.

When diagnosis keys are being submitted to the CWA backend, we store those keys on our PostgreSQL database, along with the timestamp at which we received the keys (the "submission timestamp"). During each hourly distribution run, the retention policy is being applied. This policy deletes all diagnosis keys from the database that are older than 14 days (by submission timestamp). Later on, during the assembly of the export packages, the shifting policy ensures, that there are always at least 140 keys in each export package. If there have been too few submissions since the last distribution, this policy will "shift" all the not-yet-distributed keys to future exports, until at least 140 keys can be assembled into one file. Once a file has been assembled, this counter starts anew.

The way the distribution module is designed, is that the mapping of diagnosis keys to export files depends entirely on the database content and the submisison timestamps of the keys. Now, if after 14 days, the retention policy deletes over 14 day old keys from the database, this 140 key threshold might be reached in different export files than they were before the keys were deleted. This leads to the "repackaging" of some of the keys into new/different export files - which is, of course, undesirable.

In order to address the issue, we have decided to (and already started to implement):
1. Generate empty export files for every hour/day that the 140 key threshold was not reached
2. Also include empty dates/hours into the respective index files
3. Prevent the "updating" of files that are already on the object store (except for index files and the app config)

Again, thank you very much for reporting this! We will keep this issue open and link the respective pull request, once the issue is resolved.
