### ISSUE TITLE
hour files are created with 0 keys

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#699]
## Describe the bug
sine today 11:05 hour files are created for each hour and each date sine 24-07-2020, 
even no key is included.

## Expected behaviour
only create hour files with keys.

**Comment by GPclips** [comment]
Hello @Tho-Mat,

I will forward this to our dev team.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat ,

This is expected behavior if the 140 key threshold was not reached for an hour/day. I refer to the [comment](https://github.com/corona-warn-app/cwa-server/issues/650#issuecomment-656209111) by @pithumke in #650:

In order to address the issue, we have decided to (and already started to implement):

- Generate empty export files for every hour/day that the 140 key threshold was not reached
- Also include empty dates/hours into the respective index files
- Prevent the "updating" of files that are already on the object store (except for index files and the app config)

**Comment by Tho-Mat** [comment]
@EvgeniiSkrebtcov 
Thanks for explanation.

Ok.  I see #650 is now fixed. :-) 

But I do not see why it is necessary to create empty hour/day files. 
You could just remove the hours or dates from the hour- and date-index-files if they are expired, 
but that's only a design question and not so important. 
I did not look in the code, but I think you iterate the hours and dates now.

By the why, does the ENF accept key files with less than 140 keys (a date with no reported infections)?

**Comment by Tho-Mat** [comment]
I also noticed that the index for (examples) the hour-file 

```
2020-07-26-hour-06.zip created 26.07.2020 09:05 (German Time)
was removed at                 09.08.2020 08:05 (German Time)

2020-07-26-hour-08.zip created 26.07.2020 11:05 (German Time)
was removed at                 09.08.2020 10:05 (German Time)
```

shouldn't they be removed one hour later to have them 14 Days on the server?

**Comment by fredrb** [comment]
> But I do not see why it is necessary to create empty hour/day files.
> You could just remove the hours or dates from the hour- and date-index-files if they are expired,
> but that's only a design question and not so important.
> I did not look in the code, but I think you iterate the hours and dates now.
> 
> By the why, does the ENF accept key files with less than 140 keys (a date with no reported infections)?

As far as I know, empty files were needed to avoid the distribution run to generate older files with duplicated keys in case they were bundled together due to shifting policy. And my understanding is that ENF will accept any number of keys in the file, we choose to go with at least 140 keys for privacy reasons. 

> shouldn't they be removed one hour later to have them 14 Days on the server?

I quickly checked and I think you are correct. It seems that we are retaining keys for 13 days and 23 hours, and not 14 as expected. I'll have a look in this in more detail. Thanks for pointing out!

**Comment by EvgeniiSkrebtcov** [comment]
> @EvgeniiSkrebtcov
> Thanks for explanation.
> 
> Ok. I see #650 is now fixed. :-)
> 
> But I do not see why it is necessary to create empty hour/day files.
> You could just remove the hours or dates from the hour- and date-index-files if they are expired,
> but that's only a design question and not so important.
> I did not look in the code, but I think you iterate the hours and dates now.
> 
> By the why, does the ENF accept key files with less than 140 keys (a date with no reported infections)?


 @Tho-Mat , we evaluated variety of options to resolve #650 and decided to generate empty export files to
to prevent the upload of new files (not just the update of existing files) and even prevent the (incorrect) update of index files. As, due to the shifting policy, it may happen that new hour/day files are being created in the past that were not there before. 

Exposure notification server [spec](https://developer.apple.com/documentation/exposurenotification/setting_up_an_exposure_notification_server)
defines the following protobuf
`message TemporaryExposureKeyExport {
...
    // The temporary exposure keys themselves.
    repeated TemporaryExposureKey keys = 7;`
where is repeated field rule can be repeated any number of times (including zero) in a well-formed message.
This edge case was also part of our testing.

For the issue with deletion time, we will create a separate issue and link to the original discussion.

**Comment by Tho-Mat** [comment]
so this can be closed now
