### ISSUE TITLE
time difference between upload and publish

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#755]
How long is the time difference between the key upload time and the time they are published?

Or more precise:
If keys are uploaded 23:00:00-23:59:59, will they be added to the 23:00-hour-file (assume more than 140 keys exists)
or is it possible they will be added to the 0:00-hour-file, if they come later for example after 23:55:00.
Then the time difference would be **5** min.

**Reason** for the question:
On 2020-07-10-07 the hour-00 file looks like all keys have been uploaded on 2020-07-09
45 keys from 18:00 to 19:00
65 keys from 22:00 to 23:00
60 keys form 00:00 to 01:00  << this one looks as if it has been uploaded before 0:00 but added after 0:00
the 60 keys are: 
5x6 08.07
5x8 07.07 5x8 06.07 5x8 05.07
5x5 04.07
5x3 03.07
5x1 02.07 5x1 01.07 5x1 30.06 5x1 29.06 5x1 28.06 5x1 27.06

key | risk | date | period
-- | -- | -- | --
...83d | 1 | 26.06. | 2655216
...1d1 | 1 | 26.06. | 2655216
...601 | 1 | 26.06. | 2655216
...224 | 1 | 26.06. | 2655216
...f7b | 1 | 26.06. | 2655216
...ccf | 1 | 27.06. | 2655360
...1ac | 1 | 27.06. | 2655360
...798 | 1 | 27.06. | 2655360
...827 | 1 | 27.06. | 2655360
...0c2 | 1 | 27.06. | 2655360
...295 | 1 | 28.06. | 2655504
...204 | 1 | 28.06. | 2655504
...c71 | 1 | 28.06. | 2655504
...ebe | 1 | 28.06. | 2655504
...c8b | 1 | 28.06. | 2655504
...b02 | 1 | 29.06. | 2655648
...d13 | 1 | 29.06. | 2655648
...278 | 1 | 29.06. | 2655648
...79a | 1 | 29.06. | 2655648
...e62 | 1 | 29.06. | 2655648
...c06 | 1 | 30.06. | 2655792
...97d | 1 | 30.06. | 2655792
...9d2 | 1 | 30.06. | 2655792
...534 | 1 | 30.06. | 2655792
...d79 | 1 | 30.06. | 2655792
...432 | 1 | 01.07. | 2655936
...a9e | 1 | 01.07. | 2655936
...873 | 1 | 01.07. | 2655936
...38c | 1 | 01.07. | 2655936
...4e4 | 1 | 01.07. | 2655936
...643 | 1 | 02.07. | 2656080
...020 | 1 | 02.07. | 2656080
...604 | 1 | 02.07. | 2656080
...94b | 1 | 02.07. | 2656080
...ff8 | 1 | 02.07. | 2656080
...32c | 3 | 03.07. | 2656224
...045 | 3 | 03.07. | 2656224
...739 | 3 | 03.07. | 2656224
...d07 | 3 | 03.07. | 2656224
...dd3 | 3 | 03.07. | 2656224
...c7b | 5 | 04.07. | 2656368
...087 | 5 | 04.07. | 2656368
...86c | 5 | 04.07. | 2656368
...fc4 | 5 | 04.07. | 2656368
...1c4 | 5 | 04.07. | 2656368
...e37 | 6 | 08.07. | 2656944
...085 | 6 | 08.07. | 2656944
...8c3 | 6 | 08.07. | 2656944
...082 | 6 | 08.07. | 2656944
...30c | 6 | 08.07. | 2656944
...85f | 8 | 05.07. | 2656512
...806 | 8 | 05.07. | 2656512
...1f4 | 8 | 05.07. | 2656512
...a3e | 8 | 05.07. | 2656512
...7c7 | 8 | 05.07. | 2656512
...eaf | 8 | 06.07. | 2656656
...117 | 8 | 06.07. | 2656656
...6d4 | 8 | 06.07. | 2656656
...4b3 | 8 | 06.07. | 2656656
...301 | 8 | 06.07. | 2656656
...0c0 | 8 | 07.07. | 2656800
...716 | 8 | 07.07. | 2656800
...ffc | 8 | 07.07. | 2656800
...6e0 | 8 | 07.07. | 2656800
...0ac | 8 | 07.07. | 2656800

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat ,

The diagnosis keys need to be expired for at least two hours, before they can be distributed. This means that if the key has been submitted within two hours after the expiry date, it cannot be published immediately. Therefore a distribution timestamp is calculated, which is either the submission timestamp, or, if the submission timestamp is within two hours after the expiry date, the expiry date plus two hours. This ensures compliance with the specification from Google and Apple.

**Comment by Tho-Mat** [comment]
@EvgeniiSkrebtcov 
Sorry I do not understand what you mean with "expiry date". (Isn't this 14days?) 
Could you make an example for each case with submitting time and date in UTC?

**Comment by EvgeniiSkrebtcov** [comment]
Hello @Tho-Mat,

I referred to an expired Diagnosis key in the sense that it is no longer used by the mobile device.  

For each submitted key Distribution service calculates the earliest point in time at which a key can be distributed according to the following rule:
- Before a key is allowed to be distributed, it must be expired for a configured amount of time (currently 2 hours).

See [ProdDiagnosisKeyBundler.java](https://github.com/corona-warn-app/cwa-server/blob/f3d66840ef59e2ced10fb9b42f08a8938e76075a/services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/ProdDiagnosisKeyBundler.java#L116) for implementation details.

- a still valid Diagnosis key will be embargoed and not included it in any batches, until after it has expired + 2 hours to handle skew
- Diagnosis keys that already expired at least 2 hours back, will be picked up by the next Distribution service run, that is scheduled to run every hour 
`  schedule: '5 * * * *'`
and added to the hourly package (considering that there are enough keys to create a package, otherwise shifting policy applies)

**Comment by EvgeniiSkrebtcov** [comment]
Hello, @Tho-Mat 

Kindly let me know in case further clarification needed.
