### ISSUE TITLE
Same day keys are published by the app but the server published them on the next day

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-server#856]
## Describe the bug
ToDay keys are now published by the app but are shifted to the next day.

## Expected behaviour
Today or same day keys should be publish the day they are uploaded.

## Steps to reproduce the issue
At the moment nearly 50% of the users upload a key for the day they upload their keys.
Take a look at 2020-10-05.zip and 2020-10-06-hour-03.zip
I first saw this on 2020-09-15, 2020-09-17, 2020-09-19, (but this lonely ones may be a result of a wrong device time). 
On 2020-09-21 the number starts to increase to nearly 50% now.

## Additional context
In the day file 2020-10-05.zip at least 103-117 users publish a same day key.
(it also contains same day key from 2020-20-04 uploads.)
All keys of this users have the wrong risk values.
6,8,8,8,5,3,1,...
It should be
5,6,8,8,8,5,3,1
For the 1. key the risk is too high,
For the 2., 5., 6., 7. the risk is too low.

## links
https://github.com/corona-warn-app/cwa-app-ios/issues/1097
https://github.com/corona-warn-app/cwa-server/issues/755
https://github.com/corona-warn-app/cwa-server/issues/723

**Comment by JonasZeitzem-sap** [comment]
Hello @Tho-Mat ,
Thank you for raising this and making us aware of your observations. We have looked into it and came to the conclusion that this behavior is there because of a design decision that was made during the development of the distribution service. 
Evgenii already explained in more detail how the distribution service is working [here](https://github.com/corona-warn-app/cwa-server/issues/755#issuecomment-692942406).
In short, this behavior is caused by the embargo logic implemented on the distribution service. The Distribution service embargos all same day keys for 24 hours if it is not yet expired for more than 2 hours.
We agree that the recent change in EN implementation and our as is distribution logic results the fact that the distribution of same-day keys is delayed for a complete day.
Since this delay was implemented as an additional privacy measure, we cannot immediately change it, without a thorough analysis of the side effects.
We will re-evaluate this internally with security and DPP experts and implement it as an enhancement if there are no additional risks.
We will keep this git item open to keep you informed about the results.

**Comment by Tho-Mat** [comment]
@JonasZeitzem-sap 
Thanks for the info.
I understand that the issue is a result of the design decision.
But in the time 2020-09-24 to today up to 50% of the users upload a same day key.
Hopefully it has stopped [now](https://github.com/corona-warn-app/cwa-app-android/issues/1325#issuecomment-704883307). 
So for me it was important to rise this as urgent and give it a bug lable.
If we will see only "future-keys" from users with wrong device time(#723) from now on,
there will be no problem not to fix this, since all of the keys those users upload are [useless](https://github.com/corona-warn-app/cwa-app-ios/issues/1097).

**Comment by mlenkeit** [comment]
@Tho-Mat see https://github.com/corona-warn-app/cwa-app-android/issues/1325#issuecomment-704963862. For all we know, it has stopped and as you rightfully point out, any further "future TEKs" are most likely because of incorrect device time, which should be significantly less submissions than what we were seeing in the recent days.

**Comment by EvgeniiSkrebtcov** [comment]
@Tho-Mat ,
 
Just a quick update. We are working on improvements to our embargoing logic that will allow us to reduce unnecessary delays in key distribution. We are planning to deliver this enhancement with the next release.
