### ISSUE TITLE
new exposure keys not downloaded every day

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-server#909]
## Your Question
[ExposureChecks-2020-10-21.txt](https://github.com/corona-warn-app/cwa-server/files/5415499/ExposureChecks-2020-10-21.txt)

If I look at the exposure checks in iOS (see attachment), I notice regularly, that the same file with the maximum number of keys is downloaded (which I assume is the one containing the most recent keys) is downloaded multiple days in consecutive order.

First question: Is this assumption correct, that the largest file, is the one with the most recent keys?

If yes, then there could be two reasons, why no new keys are downloaded:
a) No new positive tests were entered
b) New positive tests are existing, but because of the server logic (packaging/batches of keys) prevents the presentation of the new keys

In the current situation I think it´s highly unlikely, that on any day (maybe just workday) no new positive tests are registered with the app.
Therefore the second question is: Is there a server logic in place, which prevents new keys from being downloaded as soon as possible? The same day or next day?

**Comment by fredrb** [comment]
Hi @mss1010 thanks for your question!

Before addressing your specific questions, let me explain the data you're seeing on the attached file.

```json
{
  "Build" : "18A8395",
  "ExportVersion" : 2,
  "ExposureChecks" : [
    	... 
  ]
}
```

 The `ExposureChecks` property contains an array of all the times your phone requested keys from our CDN. The requests are done _nearly_ on a daily basis and it should download around 14 days worth of keys. The `Files` property contains all the **daily** packages downloaded. This means that each this list should contain the package for today and all other days before. If we look at the first object as an example:

```json
        {
          "Hash" : "D63C8A25912DA34CD9A266967B854BB98BC09290BFE12B804C1FD796AE64BBD3",
          "MatchCount" : 0,
          "KeyCount" : 10876,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-21 12:37:17 +0200"
        },
        {
          "Hash" : "F049E50F243C7B991867B229668A44CBCA6E63846EBECA0A2B8E3C0BA8B7ACAC",
          "MatchCount" : 0,
          "KeyCount" : 6386,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-21 12:37:17 +0200"
        },
        {
          "Hash" : "3908E8EF3DE421C31CD585B8CBAFCEA7D54C21BF94E5E690A477AEE217E8B95A",
          "MatchCount" : 0,
          "KeyCount" : 4814,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-10-21 12:37:17 +0200"
        },
...
```

The first item (keyCount 10876) is the daily package for `2020-10-20`, the second (keyCount 6386) is the daily package for `2020-10-19` and so on. These packages will look the same for all previous entries (`ExposureChecks`) except for the top and bottom, that will contain the most recent and most old package respectively. 

All packages can be downloaded from our [public CDN](https://svc90.main.px.t-online.de), which is where the mobile is downloading the keys from. For the example above you could simply download the keys I mentioned above via the URL: https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-10-20

Obs.: You will notice that the `hash` value changes for all keys on Oct 17th. This is due to our most recent deployment of interoperability. This resulted in us needing to update all older packages already deployed in the CDN. However the number of keys is still the same.

To your questions:

> Is this assumption correct, that the largest file, is the one with the most recent keys?

No. The file with the most recent keys (from the time your downloaded) is the top one on the first `ExposureChecks` object in your JSON file: 

```json
{
  "Hash" : "D63C8A25912DA34CD9A266967B854BB98BC09290BFE12B804C1FD796AE64BBD3",
  "MatchCount" : 0,
  "KeyCount" : 10876,
  "AppBundleIdentifier" : "de.rki.coronawarnapp",
  "Timestamp" : "2020-10-21 12:37:17 +0200"
},
```

> Therefore the second question is: Is there a server logic in place, which prevents new keys from being downloaded as soon as possible? The same day or next day?

There is - but based on your previous assumptions I think this no longer relevant to this question. We have a 2 hour expiry policy that we have to follow before distributing keys for security reasons. And we also have a shifting policy to distribute packages that contain 140 keys or more, this can cause keys to not be distributed on the day they were submitted if we don't have enough keys. 

-----

Given the explanation above and my analysis on your exposure file, it seems like the data you're seeing is true to what is there on the CDN, and all files were downloaded accordingly. I noticed some off-days on the logs and days with less than 14 packages downloaded. I can't say for sure if that's intended because this logic belongs to the iOS app. If you have questions in this regard I suggest you to raise a ticket in [our iOS app repository](https://github.com/corona-warn-app/cwa-app-ios).

**Comment by mss1010** [comment]
Hello @fredrb 

thanks for the detailed explanation. Ok then I was misinterpreting it, and the question is solved.
Just one more question: I guess that the changes on October, 17th also had an effect on the key padding? Is that right?
Because on the 17th and the days before, the key counts were much higher than now, while the infection rates were lower.

**Comment by fredrb** [comment]
> I guess that the changes on October, 17th also had an effect on the key padding? Is that right?
Because on the 17th and the days before, the key counts were much higher than now, while the infection rates were lower.

Yes you are right. We removed the padding, i.e. the key padding is now set to 1. Meaning that there will be no extra keys appended to the submission. And because of this, as you correctly pointed out, the number of keys is significantly smaller now.

**Comment by mss1010** [comment]
> Yes, you are right. We removed the padding, i.e. the key padding is now set to 1. Meaning that there will be no extra keys appended to the submission. And because of this, as you correctly pointed out, the number of keys is significantly smaller now.

Ok, I see.  But if no keys are added, then the numbers still seem a bit too high if we just look at germany. For example, yesterday the key count was 18.645. That´s more than the reported cases in germany. Or are there now also the keys of the "compatible" countries included?

**Comment by fredrb** [comment]
Number of keys does not translate to number of infections. The daily package does not contain the keys for that day, they contain all the keys **submitted** on that day. Submission can have 1-14 key(s). If all submissions have 14 keys, the number of submissions received on the app is around `18645/14 = ~1285`. We can't say for sure if all the submissions had 14 keys, because it can happen that users with positive results were not using the app for at least 14 days. So if we assume that we had ~1500 infections submitted on the app and we also assume that at least 10% of the population is using the app, it matches the number we see here. Of course this is a gross approximation. A better analysis would be to count the number of Risk Level 6 keys found per daily package. Since each submission will always have only one key with Risk Level 6 we can derive the exact number of submissions.

**Comment by mss1010** [comment]
ok thanks. Then these questions are answered and I can close the ticket.
